trigger:
  - main  
  - dev/*
  - fix/*
  - feat/*
  - feature/*
  - refs/tags/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
 
- script: dotnet build . --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)' 

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './Dotnet.ToolBuilder.Api.sln'
    arguments: '--configuration $(buildConfiguration)'
