trigger:
  - main  
  - dev/*
  - fix/*
  - feat/*
  - feature/*
  - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
 
- task: GitVersion@5
  displayName: git version
  inputs:
    runtime: 'core'
    updateAssemblyInfo: true

- script: dotnet build --configuration $(buildConfiguration) . /p:Version='$(GitVersion.NuGetVersion)'
  displayName: 'dotnet build $(buildConfiguration)' 

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './Dotnet.ToolBuilder.Api.sln'
    arguments: '--configuration $(buildConfiguration)'
