trigger:
  - main  
  - dev/*
  - fix/*
  - feat/*
  - feature/*
  - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
- task: Bash@3
  displayName: dotnet install toolbuilder
  inputs:
    targetType: 'inline'
    script: 'dotnet tool install --global DotnetTool.Builder --version 9.0.0 && PATH="/root/.dotnet/tools:$PATH"'

- script: dotnet build . --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)' 

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './Dotnet.ToolBuilder.Api.sln'